# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    
    # 1. TAMBAHKAN BAGIAN INI AGAR GITHUB PUNYA IZIN MENGUNGGAH PACKAGE
    permissions:
      contents: read
      packages: write 

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 
      uses: actions/setup-java@v3
      with:
        java-version: '21' # sesuaikan dengan versi Java kamu
        distribution: 'temurin'
        server-id: github # Harus sama dengan <id> di pom.xml
        server-username: GITHUB_ACTOR
        server-password: GITHUB_TOKEN
        
    # 2. PASTIKAN TOKEN INI DISERTAKAN SAAT PERINTAH DEPLOY
    - name: Build and Deploy
      run: mvn deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
